include:
 - conf/compose.external.yaml
services:
  webwatcher:
    build:
      context: .
      dockerfile: conf/Dockerfile
      target: production
    image: katzenkralle/webwatcher:latest 
    pull_policy: build   # only build locally—never try to pull
    environment:
       # Note: use $$ to escape $ used for enviorment variables.
       # Refere to: https://docs.docker.com/reference/compose-file/interpolation/
       - APP_DEFAULT_ADMIN_USERNAME=admin
       - APP_DEFAULT_ADMIN_HASH=$$2b$$12$$SNsRVcWKAEB/h5x0tUXqQeoBwc8MY3seQFD3mPmu9Z4I6NUvQgHQS
       - CRYPTO_SECRET_KEY=51bc0c1562e265a67af236137d6b17f14e5e1c5c580c066dff775b2d53f05d04
    networks:
      - internal
      - global
    ports:
      - "80:8080"
    volumes:
      - webwatcher_data:/webwatcher/webw_serv_scripts_store
      - "/etc/timezone:/etc/timezone:ro" # to get the correct timezone
      - "/etc/localtime:/etc/localtime:ro"
    cap_add:
      - SYS_TIME

networks:
  internal:
    driver: bridge
    internal: true
  global:
    driver: bridge
    internal: false

volumes:
  mongo_data:
    driver: local
  maria_data:
    driver: local
  webwatcher_data:
    driver: local
